CREATE TABLE helyisegek(
	h_az INTEGER PRIMARY KEY AUTOINCREMENT,
	megnevezes VARCHAR(20) NOT NULL,
	alapterulet INTEGER);
CREATE TABLE idopontok(
	i_az INTEGER PRIMARY KEY AUTOINCREMENT,
	idopont DATETIME NOT NULL);
CREATE TABLE meresek(
	m_az INTEGER PRIMARY KEY AUTOINCREMENT,
	i_az INTEGER NOT NULL,
	h_az INTEGER NOT NULL,
	mertadat INTEGER NOT NULL,
	FOREIGN KEY (i_az) REFERENCES idopontok(i_az),
	FOREIGN KEY (h_az) REFERENCES helyisegek(h_az));
CREATE TABLE atlagok(
	a_az INTEGER PRIMARY KEY AUTOINCREMENT,
	datum DATE NOT NULL,
	h_az INTEGER NOT NULL,
	atlag FLOAT,
	FOREIGN KEY (h_az) REFERENCES helyisegek(h_az));
CREATE TABLE hibak(
	e_az INTEGER PRIMARY KEY AUTOINCREMENT,
	leiras VARCHAR(100) NOT NULL,
	m_az INTEGER NOT NULL,
	FOREIGN KEY (m_az) REFERENCES meresek(m_az));