/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package meresiszimulacio;

import java.awt.GridLayout;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.sqlite.JDBC;

/**
 *
 * @author Tanar
 */
public class FoAblak extends javax.swing.JFrame {

    /**
     * Creates new form FoAblak
     */
    private File dbFile;
    public FoAblak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jDialog1.setTitle("Kérdés");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setLocation(new java.awt.Point(100, 100));
        jDialog1.setMinimumSize(new java.awt.Dimension(280, 120));
        jDialog1.setModal(true);
        jDialog1.setPreferredSize(new java.awt.Dimension(300, 120));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(300, 120));

        jLabel1.setText("A meresiadatok.db létezik! Törli?");

        jButton1.setText("Igen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vege(evt);
            }
        });

        jButton2.setText("Nem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atnevezes(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mérési szimulációs program");

        jMenu1.setText("Alkalmazás");

        jMenuItem1.setText("Új szimuláció");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letrehozas(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Szimuláció megnyitása");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Szimuláció mentése");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Kilépés");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kilepes(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segítség");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Kilepes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kilepes
        if(dbFile.exists()){
            jDialog1.setVisible(true);
            /*JDialog jd=new JDialog(this,"Kérdés");
            jd.setLayout(new GridLayout(2,1));
            JPanel p1=new JPanel();
            jd.add(p1);
            JPanel p2=new JPanel();
            p2.setLayout(new GridLayout(1,2));
            
            JLabel sz1=new JLabel("Törlés?");
            p1.add(sz1);
            jd.add(p2);
            JButton b1=new JButton("Igen");
            JButton b2=new JButton("Nem");
            jd.add(b1);
            jd.add(b2);
            jd.setSize(200,100);
            jd.setVisible(true);*/
            
        }
        //
    }//GEN-LAST:event_Kilepes

    private void Letrehozas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letrehozas
        //File f=new File("meresiadatok.db");
        dbFile=new File("meresiadatok.db");
        //if(f.exists()){
        if(dbFile.exists()){
            //f.delete();
        }
        try{
            //Class.forName("org.sqlite.JDBC");
            Connection k=DriverManager.getConnection("jdbc:sqlite:meresiadatok.db");
            Statement u=k.createStatement();
            FileInputStream fis=new FileInputStream("K:\\SZFII2\\letrehozas.sql");
            Scanner sc=new Scanner(fis);
            String sql="";
            while(sc.hasNextLine()){
                String sor=sc.nextLine();
                sql+=sor;
                if(sor.endsWith(";")){
                    u.execute(sql);
                    sql="";
                }
            }
            /*sc.close();
            fis.close();
            u.close();
            k.close();*/
        }catch(Exception ex){}
    }//GEN-LAST:event_Letrehozas

    private void Vege(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vege
        this.dbFile=new File("meresiadatok.db");
        if(this.dbFile.delete()){
            System.exit(0);
        }
    }//GEN-LAST:event_Vege

    private void Atnevezes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atnevezes
        File mentes=new File("mentes.db");
        if(this.dbFile.renameTo(mentes)){
            System.exit(0);
        }
    }//GEN-LAST:event_Atnevezes

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoAblak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
